### ISSUE TITLE
Hero Image Por Favor

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Center-for-the-Humanities-at-Temple#4]
Hey Zac! When you get a chance could you find a hero for CHAT? They would like to keep the same artsy, mosaic, art piece like feel as what the center has now, but with brighter colors. Think there is something like this out there? Thank you! 

![image](https://user-images.githubusercontent.com/15130721/47094619-92843580-d1f9-11e8-8f1a-7bff3baebb5f.png)

**Comment by ZMcGroarty** [comment]
![chat_hero-min](https://user-images.githubusercontent.com/15017242/47094992-45ed2a00-d1fa-11e8-8c56-d32d16497d18.png)

**Comment by CVE82** [comment]
Thank you that was fast!
